### ISSUE TITLE
Add "Bot Tutorials" Blog

### ISSUE THREAD

**Issue by idoshamun** [elegantmonkeys/daily#1]
#### New Blog Suggestion

Name: Bot Tutorials

Link: https://tutorials.botsfloor.com/

Topic: Chatbot development & design

**Comment by idoshamun** [comment]
@keyuls, I added your suggestion so you can keep track

**Comment by idoshamun** [comment]
@keylus, I am glad to announce that we've added the blog to Daily :)

**Comment by keyuls** [comment]
Thank you for adding Bot Tutorials.  I have another suggestion too
