### ISSUE TITLE
word break missing on card

### ISSUE THREAD

**Issue by gian8** [elegantmonkeys/daily#13]
#### Bug Report

Explanation: *When in card there is a single text very long (i.e https://www.contentful.com/blog/2018/06/13/journey-cutting-edge-static-sites-gatsbyjs-v2/) the text is not wrapped in the right way in the card*

you can try to add 
```
.card-content{
word-break: break-word;
}
```

**Comment by idoshamun** [comment]
@gian8 Thanks for the report and also for solution, I will let you know when a new version is available with the fix

**Comment by idoshamun** [comment]
@gian8 Your fixed released in 1.5.6 :)

**Comment by idoshamun** [comment]
@all-contributors please add @gian8 for bug
