### ISSUE TITLE
Blog Suggestion -> Alligator.io

### ISSUE THREAD

**Issue by tomma5o** [elegantmonkeys/daily#14]
Hi!
Very useful extension guys!
I'd like to see this blog in the search, this blog publish very useful and well-written article about our ecosystem.
Thanks in advance ;)

#### New Blog Suggestion

Name: *Alligator*

Link: *https://alligator.io*

Topic: *Front-End Development*

**Comment by idoshamun** [comment]
@tomma5o Thanks for suggestion, I'll take a look and let you know :)

**Comment by idoshamun** [comment]
Enjoy Alligator blog, it is online on Daily :)

**Comment by tomma5o** [comment]
Thank you guys! <3
