### ISSUE TITLE
Similar Firefox add on

### ISSUE THREAD

**Issue by RamRama** [elegantmonkeys/daily#2]
As you guys might know, firefox has released their new quantum browser and I am thinking about migrating from chrome to firefox but I really like your extention, can you guys make a firefox add on please?

#### Feedback
One word - AMAZING 👍

**Comment by idoshamun** [comment]
@RamRama I am also thinking about migrating :P

Right now we really focus on improving our content and making a better ranking system but a Firefox version is totally something that we look for and planning, it will take time though.

Thanks for the great feedback!

**Comment by idoshamun** [comment]
@RamRama I am glad to announce that we launched our Firefox addition of Daily today:
https://addons.mozilla.org/en-US/firefox/addon/daily/

**Comment by RamRama** [comment]
@idoshamun  thanks a lot, I really appreciate it 👍

**Comment by idoshamun** [comment]
Looking for your thoughts and feedback for making Daily better :)

**Comment by idoshamun** [comment]
@all-contributors please add @ram-mar for ideas
