### ISSUE TITLE
Daily - Firefox add-ons link wrong.

### ISSUE THREAD

**Issue by MRRaduan** [elegantmonkeys/daily#3]
#### Bug Report

Explanation: *Firefox add-ons link wrong.*

Reproduce: 

- *Enter [Daily Website](https://www.dailynow.co/);*
- *Click on button [FIREFOX ADD-ONS](https://www.dailynow.co/) at the right side of CHROME WEB STORE button;*
- ***Page not found** in Firefox add-ons page .*

Version: *1.1.1 (**according Chrome's extension page**)*

Browser version: *Mozilla Firefox Quantum 57.0.4 (64-bit)*

OS: *Elementary OS - Built on "Ubuntu 16.04.3 LTS" - Linux 4.10.0-42-generic*

Screenshot:
![screenshot from 2018-01-13 15-51-59](https://user-images.githubusercontent.com/29872022/34908709-1b94dd60-f87b-11e7-8228-dca0c1bcadb5.png)

#### Feedback

*Some developers recommended the Daily, it's very helpful and I was anxious for use it, but Firefox add-ons link is not available. I want to use Daily.*

**Comment by idoshamun** [comment]
Hi Matheus,

The link is not broken but we currently have an issue with the Firefox
version that we have to resolve. I hope to resolve it soon, we are doing
our best.
In the meantime you can enjoy the Chrome version.

**Comment by MRRaduan** [comment]
No problem!
Thanks for answer Ido.

**Comment by idoshamun** [comment]
@MRRaduan I am glad to announce that Firefox version is available once more :)
