### ISSUE TITLE
One click "add to Pocket" feature

### ISSUE THREAD

**Issue by heron182** [elegantmonkeys/daily#4]
#### Feature Suggestion

It would be nice if I could add an article to my *pocket* app  in one click for later reading, just like I can copy the link to clipboard or share it on Twitter / Facebook, etc.

**Comment by idoshamun** [comment]
Hi @heron182,

Thanks for your feedback we highly appreciate it.
We checked the possibility for adding Pocket button and Pocket doesn't allow to customize their button and adjust it to Daily needs. In addition we are would like to add bookmarks mechanism in the future which will provide similar functionality.

For the time being I'll close the issue, let me know if there is something else I can assist
