### ISSUE TITLE
Choice for sharing sites

### ISSUE THREAD

**Issue by Ornataweaver** [elegantmonkeys/daily#9]
The share button for links only has fb, twitter & linkedin.
If you make a settings for users, let them choose which sites to share the links on.
There can be many sites as you know, the list can be long. You can still set the limit of chosen sites up to 3 or up to 5.

**Comment by idoshamun** [comment]
Could you list more sites that you would like to share to please?

**Comment by Ornataweaver** [comment]
Of course; Medium, Telegram. Reddit would be useful for some people.
My point is sharing daily as quickly as it can get. Through every medium related to dev culture. 
I also prefer to unselect fb and linkedin from my view.

**Comment by idoshamun** [comment]
Thanks for the list we'll take it into consideration for our next product planning

**Comment by idoshamun** [comment]
@Ornataweaver as you might have seen, in the latest version of Daily there is no more sharing buttons but bookmark. I am closing this issue as it may not be relevant anymore but if we ever add back sharing buttons we might use the sites you suggested :) Thanks!

**Comment by idoshamun** [comment]
Currently we are not considering moving to GitLab.
